name = "neurovolt"
main = "src/index.js"
compatibility_date = "2024-01-01"
nodejs_compat = true

[build]
command = "npm run build"

[env.production]
name = "neurovolt-production"

[env.staging]
name = "neurovolt-staging" 