"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "neurovolt"
# Set this to today's date
compatibility_date = "2026-03-21"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"